# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meowbook', '0002_auto_20160116_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscomment',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='status_comments', to='meowbook.CatStatus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statuscomment',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meowbook.CatProfile'),
        ),
    ]
