# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meowbook', '0003_auto_20160116_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='picturecomment',
            name='picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='picture_comments', to='meowbook.CatPicture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picturecomment',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meowbook.CatProfile'),
        ),
    ]
